PANDOC = /usr/bin/pandoc
HTMLFILE = e-soh-requirements-doc.html
BROWSER = chromium

html: pandoc

pandoc:
	date -u +'E-SOH requirements document, generated by pandoc %F %T UTC' > pandoc.TMP
	echo "" >> pandoc.TMP
	cat introduction/* >> pandoc.TMP
	echo "" >> pandoc.TMP
	cat dependencies/* >> pandoc.TMP
	echo "" >> pandoc.TMP
	cat business-requirements/* >> pandoc.TMP
	echo "" >> pandoc.TMP
	cat user-requirements/* >> pandoc.TMP
	echo "" >> pandoc.TMP
	cat functional-and-non-functional-requirements/* >> pandoc.TMP
	echo "" >> pandoc.TMP
	cat risks/* >> pandoc.TMP
	echo "" >> pandoc.TMP
	cat conclusion/* >> pandoc.TMP
	echo "" >> pandoc.TMP
	$(PANDOC) -s --toc -c pandoc.css -f markdown -t html pandoc.TMP > $(HTMLFILE)
	rm pandoc.TMP
	$(BROWSER) $(HTMLFILE)

clean:
	rm -f $(HTMLFILE)

